services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-course-qdrant
    ports:
      - "9333:6333"
      - "9334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped
